dependencies:
- name: demo041205
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: voting-vote
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: voting-worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
